# Generated by Django 5.1.6 on 2025-02-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0003_booking_remove_menuitem_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("price", models.IntegerField()),
                (
                    "menu_item_description",
                    models.TextField(default="", max_length=1000),
                ),
            ],
        ),
    ]
